version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    ignore:
      - dependency-name: laravel/framework
        versions:
          - 6.20.19
