name: Laravel PHPunit test
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # - uses: nathanheffley/laravel-phpunit-action@master
      - name: Laravel PHPunit test
        run: |
          composer install --prefer-dist
          cp .env.example .env
          php artisan key:generate
          php vendor/bin/phpunit